export const languages: { label: string, value: string }[] = [
    { label: 'English', value: 'en' },
    { label: 'Japanese', value: 'ja' },
    { label: 'Korean', value: 'ko' },
    { label: 'Chinese (Simplified)', value: 'zh' },
    { label: 'Chinese (Traditional)', value: 'zh-hk' },
    { label: 'Spanish', value: 'es' },
    { label: 'Spanish (Latam)', value: 'es-la' },
    { label: 'Portuguese', value: 'pt' },
    { label: 'Portuguese (Brazil)', value: 'pt-br' },
    { label: 'French', value: 'fr' },
    { label: 'German', value: 'de' },
    { label: 'Italian', value: 'it' },
    { label: 'Russian', value: 'ru' },
    { label: 'Turkish', value: 'tr' },
    { label: 'Vietnamese', value: 'vi' },
    { label: 'Thai', value: 'th' },
    { label: 'Indonesian', value: 'id' },
    { label: 'Polish', value: 'pl' },
    { label: 'Dutch', value: 'nl' },
    { label: 'Arabic', value: 'ar' },
    { label: 'Persian', value: 'fa' },
    { label: 'Hindi', value: 'hi' },
    { label: 'Filipino', value: 'tl' },
    { label: 'Czech', value: 'cs' },
    { label: 'Hungarian', value: 'hu' },
    { label: 'Romanian', value: 'ro' },
    { label: 'Bulgarian', value: 'bg' },
    { label: 'Ukrainian', value: 'uk' },
];
